name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build image
        run: docker build -t server:latest .
      - name: Create container
        run: docker run -p 80:8080 -d server:latest
      - name: Dependencies
        run: pip install -r requirements.txt
      - name: Test
        run: python3 client.py